language: cpp
sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-8
            - ninja-build
          sources: &sources
            - ubuntu-toolchain-r-test
      compiler: gcc

before_script:
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_CXX=g++-8 -DCMAKE_BUILD_TYPE=Release -G Ninja

script:
  - ninja
