language: cpp
sudo: true

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-8
          sources: &sources
            - ubuntu-toolchain-r-test
      compiler: gcc

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake -H. -B build -DCMAKE_CXX=g++ -DCMAKE_BUILD_TYPE=Release

script:
  - make -C build -j 2
