language: cpp
sudo: required
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: g++-8, ninja-build, nodejs
script:
  - export CXX=g++8
  - mkdir -p build && cd build && cmake .. -G Ninja && ninja
