.TH "msg2" 1 "17 Oct 2018" "" ""
.SH NAME
msg2 \- output a blue arrow followed by white text
.SH SYNOPSIS
.B msg2
.IR message ...
.SH DESCRIPTION
.B msg2
outputs a blue arrow (->) followed by all given arguments,
as a space separated white string.
.SH BUGS
Only unknown bugs so far. Bugs can reported at https://github.com/xyproto/msg2/issues.
.SH VERSION
1.0.0
.SH AUTHOR
.B msg2
was written by Alexander F. Rødseth <xyproto@archlinux.org>
