.TH "msg2" 1 "18 Oct 2018" "" ""
.SH NAME
msg2 \- output a blue arrow followed by gray text
.SH SYNOPSIS
.B msg2
.IR message ...
.SH DESCRIPTION
.B msg2
outputs a blue arrow followed by all given arguments,
as a space separated string of bold text.
.sp
The arrow looks like this: ->
.sp
The first argument may be a format string, where %s's are replaced
with the rest of the arguments.
.SH OPTIONS
.TP
.BR \-v ", " \-\-version
Output the name and version number.
.SH BUGS
Only unknown bugs so far. Bugs can reported at https://github.com/xyproto/msg2/issues.
.SH VERSION
1.1.0
.SH AUTHOR
.B msg2
was written by Alexander F. Rødseth <xyproto@archlinux.org>
